apiVersion: apps/v1
kind: Deployment
metadata:
  name: priporocilni-sistemi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: priporocilni-sistem
  template:
    metadata:
      labels:
        app: priporocilni-sistem
    spec:
      containers:
        - image: aquawhale/priporocilni-sistem
          name: priporocilni-sistem
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: priporocilni-sistem
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: priporocilni-sistem