apiVersion: apps/v1
kind: Deployment
metadata:
  name: priporocilni-sistemi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priporocilni-sistemi-master
  template:
    metadata:
      labels:
        app: priporocilni-sistemi-master
    spec:
      containers:
        - image: mm9136/priporocilni-sistemi-master
          name: priporocilni-sistemi-master
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: priporocilni-sistemi-master
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: priporocilni-sistemi-master
