kumuluzee:
  name: priporocilni-sistemi
  version: 1.0.0
  env:
    name: dev
  openapi:
    ui:
      enaled: true
  server:
    base-url: http://localhost:8081/v1
    http:
      port: 8081
integration-properties:
    host: montanaflynn-spellcheck.p.rapidapi.com
    api-key: c1a417f21cmshf584f138be3c98bp1eb29fjsn2995f2f6e3ac
